return {
    {val=44,name="TF2 Heavy (Spun Up with Brass Beast)"},
    {val=80,name="TF2 scoped Sniper, Soldier charging Mangler"},
    {val=100,name="gMod Sandbox Default Walk Speed, HL:S Walk Speed"},
    {val=110,name="TF2 Heavy (Spun Up)"},
    {val=150,name="HL2 Walk Speed"},
    {val=160,name="TF2 Sniper with drawn Huntsman"},
    {val=190,name="HL2 Run Speed"},
    {val=200,name="gMod Sandbox Default Run Speed"},
    {val=230,name="TF2 Heavy"},
    {val=240,name="TF2 Soldier"},
    {val=270,name="TF2 Engineer hauling a building, HL:S DM Run Speed"},
    {val=280,name="TF2 Demoman"},
    {val=300,name="TF2 Pyro, Engineer, Sniper"},
    {val=308,name="TF2 Demoman with boots and shield"},
    {val=320,name="HL2 Sprint Speed, HL:S Run Speed, TF2 Medic and Spy"},
    {val=345,name="TF2 Pyro with Powerjack"},
    {val=360,name="TF2 Scout with Baby Face's Blaster at 0% boost"},
    {val=400,name="gMod Sandbox Default Sprint Speed, TF2 Scout "},
    {val=520,name="TF2 Scout with Baby Face's Blaster at max boost"},
}