
apadventure.toolgroup=apAdventure

tool.apadventure_save.name=Save Marker
tool.apadventure_save.desc=Mark Entities that will be saved to the Config
tool.apadventure_save.left=Mark Entity
tool.apadventure_save.right=Unmark Entity

tool.apadventure_delete.name=Delete Marker
tool.apadventure_delete.desc=Mark Map-Created Entities to be deleted when the Config is loaded
tool.apadventure_delete.left=Mark Entity
tool.apadventure_delete.right=Unmark Entity
tool.apadventure_delete.creationmode=Current Mode: Creation ID
tool.apadventure_delete.namemode=Current Mode: Targetname

tool.apadventure_exit.name=Exit
tool.apadventure_exit.desc=Place Exits that Players will leave the map through
tool.apadventure_exit.left=Place/Update Exit
tool.apadventure_exit.right=Copy Settings

tool.apadventure_entrance.name=Entrance
tool.apadventure_entrance.desc=Place Entrances that Players will enter the map through
tool.apadventure_entrance.left=Place/Update Entrance
tool.apadventure_entrance.reload=Place Entrance at your feet

tool.apadventure_start.name=Start
tool.apadventure_start.desc=Place Start Points that Players may start their run on
tool.apadventure_start.left=Place/Update Start
tool.apadventure_start.reload=Place Start at your feet

tool.apadventure_location.name=Location
tool.apadventure_location.desc=Place Locations
tool.apadventure_location.left=Place/Update Locations

tool.apadventure_inspector.name=Inspector
tool.apadventure_inspector.desc=Shows Information about normally invisible entities
tool.apadventure_inspector.left=Hide/Unhide Inspector Info
tool.apadventure_inspector.reload=Request Update

apadventure.editor.nicename.label=Nice Name
apadventure.editor.walkspd.label=Walk Speed
apadventure.editor.runspd.label=Run Speed
apadventure.editor.sprintspd.label=Sprint Speed
apadventure.editor.jump.label=Jump Power
apadventure.editor.grav.label=Gravity
apadventure.editor.frctn.label=Player Friction
apadventure.editor.accel.label=Player Acceleration
apadventure.editor.airaccel.label=Player Air Acceleration
apadventure.editor.stopspd.label=Player Stop Speed
apadventure.editor.hev.label=Enable HL2 HEV Suit functionality (Energy drain from sprinting, using flashlight, etc.)

apadventure.editor.prioentr.label=Connect this Regions entrances before other Regions in the Map
apadventure.editor.regammo.label=Ammo Availability