apadventure.editor.require.gametagdesc=Game: 
apadventure.editor.require.wsidtagdesc=Workshop Item: 

apadventure.requiretag.wire.name=Wiremod
apadventure.requiretag.wire.desc=Checks if Wiremod is installed, Wiremod Canary and manual installations are also recognized.
apadventure.requiremsg.wire.manual=Wiremod seems to be installed manually. Make sure that your Wiremod installation is up to date.

apadventure.requiretag.gmdoom.name=gmDoom
apadventure.requiretag.gmdoom.desc=Checks if gmDoom is installed and if a .wad file exists in the Players garrysmod folder.
apadventure.requiremsg.gmdoom.noinstall=gmDoom loads Doom assets from a Doom 2 IWAD, which you'll have put in your garrysmod directory, so you should follow the setup instructions on the workshop page and make sure it works in Sandbox first if you haven't done so already.
apadventure.requiremsg.gmdoom.nowad=No .wad files were found in your garrysmod folder for gmDoom to use. Make sure you have installed gmDoom properly.
apadventure.requiremsg.gmdoom.haswad=gmDoom is mounted and a .wad file exists in the garrysmod folder.\nHowever, apAdventure does not know whether the wad file is a valid Doom 2 IWAD, so you may want to test gmDoom in Sandbox to make sure it works if you've never used it before.