
apadventure.toolgroup=apAdventure
apadventure.category=apAdventure
apadventure.entity.damagetest=Damage Tester
apadventure.entity.entrance=apAdventure Entrance 
apadventure.entity.exit=apAdventure Exit
apadventure.entity.location=apAdventure Location
apadventure.entity.start=apAdventure Start Point

apadventure.toolui.region=Region

tool.apadventure_save.name=apAdventure Save Marker
tool.apadventure_save.shortname=Save Marker
tool.apadventure_save.desc=Mark Entities that will be saved to the Config
tool.apadventure_save.left=Mark Entity
tool.apadventure_save.right=Unmark Entity

tool.apadventure_delete.name=apAdventure Delete Marker
tool.apadventure_delete.shortname=Delete Marker
tool.apadventure_delete.desc=Mark Map-Created Entities to be deleted when the Config is loaded
tool.apadventure_delete.left=Mark Entity
tool.apadventure_delete.right=Unmark Entity
tool.apadventure_delete.creationmode=Current Mode: Creation ID
tool.apadventure_delete.namemode=Current Mode: Targetname

tool.apadventure_exit.name=apAdventure Exit
tool.apadventure_exit.shortname=Exit
tool.apadventure_exit.desc=Place Exits that Players will leave the map through
tool.apadventure_exit.left=Place/Update Exit
tool.apadventure_exit.right=Copy Settings
tool.apadventure_exit.region_help=The Region this Exit is in. The Generator won't use the Exit if it can't find a Region with this name.
tool.apadventure_exit.name_ui=Exit Name
tool.apadventure_exit.name_help=The name of this Exit. You can place multiple Exits with the same name if you want.
tool.apadventure_exit.match_names_info=All Exit sharing the same name should also be in the same Region. If they are not, the game will arbitrarily pick one when creating the logic files for the Generator. It may even pick a Region Name that doesn't exist, causing all Exits with that name to go unused. 

tool.apadventure_entrance.name=apAdventure Entrance
tool.apadventure_entrance.shortname=Entrance
tool.apadventure_entrance.desc=Place Entrances that Players will enter the map through
tool.apadventure_entrance.left=Place/Update Entrance
tool.apadventure_entrance.right=Copy Settings
tool.apadventure_entrance.reload=Place Entrance at your feet
tool.apadventure_entrance.region_help=The Region this Entrance is in. The Generator won't use the Entrance if it can't find a Region with this name.
tool.apadventure_entrance.name_ui=Entrance Name
tool.apadventure_entrance.name_help=The name of this Entrance. You can (and should) place multiple Entrances with the same name to give players alternative spawn points in case one of the others is obstructed.
tool.apadventure_entrance.match_names_info=All Entrances sharing the same name should also be in the same Region. If they are not, the game will arbitrarily pick a Region when creating the logic files for the Generator. It may even pick a Region Name that doesn't exist, causing all Entrances with that name to go unused. 

tool.apadventure_start.name=apAdventure Start Point
tool.apadventure_start.shortname=Start Point
tool.apadventure_start.desc=Place Start Points that Players may start their run on
tool.apadventure_start.left=Place/Update Start
tool.apadventure_start.right=Copy Settings
tool.apadventure_start.reload=Place Start at your feet
tool.apadventure_start.region_help=The Region this Start Point is in. The Generator won't use it if it can't find a Region with this name.
tool.apadventure_start.help1=Start Points tell the Generator that a run can be started from a certain Region in a certain Map. Don't place them in Maps/Regions where you don't want runs to start from.
tool.apadventure_start.help2=Start Points also function as Spawn Points. You can (and should) place multiple Start Points in the same Region to give players alternative Spawn Points in case one of the others is obstructed.

tool.apadventure_location.name=apAdventure Location
tool.apadventure_location.shortname=Location
tool.apadventure_location.desc=Place Locations
tool.apadventure_location.left=Place/Update Locations
tool.apadventure_location.right=Copy Settings
tool.apadventure_location.region_help=The Region containing this Location. The Generator won't use the Location if it can't find a Region with this name.
tool.apadventure_location.name_ui=Location Name
tool.apadventure_location.name_help=The name of this Location. There shouldn't be two Locations with the same name on the same map. It should also not be a number.
tool.apadventure_location.isdummy=Is Dummy
tool.apadventure_location.isdummy_help=Whether or not this Location is a Dummy Location. Dummy Locations won't actually be placed when the config is loaded, and are instead intended to be sent through other means like the Config Script.

tool.apadventure_inspector.name=apAdventure Inspector
tool.apadventure_inspector.shortname=Inspector
tool.apadventure_inspector.desc=Shows Information about normally invisible entities
tool.apadventure_inspector.left=Hide/Unhide Inspector Info
tool.apadventure_inspector.reload=Request Update

apadventure.editor.nicename.label=Nice Name
apadventure.editor.walkspd.label=Walk Speed
apadventure.editor.runspd.label=Run Speed
apadventure.editor.sprintspd.label=Sprint Speed
apadventure.editor.jump.label=Jump Power
apadventure.editor.grav.label=Gravity
apadventure.editor.frctn.label=Player Friction
apadventure.editor.accel.label=Player Acceleration
apadventure.editor.airaccel.label=Player Air Acceleration
apadventure.editor.stopspd.label=Player Stop Speed
apadventure.editor.hev.label=Enable HL2 HEV Suit functionality (Energy drain from sprinting, using flashlight, etc.)

apadventure.editor.prioentr.label=Connect this Regions entrances before other Regions in the Map
apadventure.editor.regammo.label=Ammo Availability

apadventure.connect.address=Address
apadventure.connect.slotname=Slot Name
apadventure.connect.password=Password
apadventure.connect.connect=Connect