
apadventure.guidefolder=en

apadventure.toolgroup=apAdventure
apadventure.category=apAdventure
apadventure.entity.damagetest=Damage Tester
apadventure.entity.entrance=apAdventure Entrance 
apadventure.entity.exit=apAdventure Exit
apadventure.entity.location=apAdventure Location
apadventure.entity.start=apAdventure Start Point

apadventure.toolui.region=Region
apadventure.toolui.twoway=If an exit and an entrance share the same name and region the Generator will pair them together as a two-way connection and ensure that you'll be able go back the way you came if it gets connected to another Two-way.

tool.apadventure_save.name=apAdventure Save Marker
tool.apadventure_save.shortname=Save Marker
tool.apadventure_save.desc=Mark entities that will be saved to the Config
tool.apadventure_save.left=Mark entity
tool.apadventure_save.right=Unmark entity
tool.apadventure_save.help1=This tool is used to mark entities that should be saved as part of your config.
tool.apadventure_save.help_dupe=Entities you mark are saved and placed using gMods duplication system, so everything that can be saved by that system can also be saved to your config. This also means that if the entities you save with it have any special behaviours when being saved to or loaded from a dupe, they'll also exhibit those behaviours when saved to or loaded from a config, regardless of whether they're being loaded when playing the gamemode or for editing.
tool.apadventure_save.help_constr=Note that the Dupe System will also copy all entities that are connected to your marked entities by constraints, including map entities, so it may create copies of already existing map entities. This should not cause any problems with entities that have been constrained to the world though.
tool.apadventure_save.dohalos=Draw green halos around marked entities

tool.apadventure_delete.name=apAdventure Delete Marker
tool.apadventure_delete.shortname=Delete Marker
tool.apadventure_delete.desc=Mark map-created entities to be deleted when the Config is loaded
tool.apadventure_delete.left=Mark entity
tool.apadventure_delete.right=Unmark entity
tool.apadventure_delete.reload=Cycle Modes
tool.apadventure_delete.creationmode=Current Mode: Creation ID
tool.apadventure_delete.namemode=Current Mode: Targetname
tool.apadventure_delete.help1=This tool allows you to mark entities that are part of the Map that should be deleted when the Config is loaded. You may mark entities to be deleted based on their Map Creation ID or Hammer Targetname.
tool.apadventure_delete.help_cid=A Creation ID is assigned to every entity when the map is compiled. The Map Creator has no control over what ID entities end up with, so you might have to reassign these if the map your config is for ever gets updated.
tool.apadventure_delete.help_targetname=A Targetname may be assigned to an entity by the Map Creator. They're normally used to tell Map I/O Events which entities they should target, so entities that don't need to receive them might not have a Targetname. Multiple entities may have the same Targetname.
tool.apadventure_delete.help_point_template=Some entities found on the map may not be directly deletable by this tool because they have been spawned in a point_template entity. In cases like that, you can try finding the point_template spawning them with the Inspector Tool and delete that instead. More info about point_template entities can be found in the Inspector Tools description.
tool.apadventure_delete.idlist.label=Marked by Creation ID
tool.apadventure_delete.idlist.cid=ID
tool.apadventure_delete.idlist.classname=Classname
tool.apadventure_delete.idlist.targetname=Targetname
tool.apadventure_delete.idlist.delbtn=Unmark selected
tool.apadventure_delete.idlist.markbtn=Mark by ID
tool.apadventure_delete.dohalos=Draw red halos around marked entities

tool.apadventure_exit.name=apAdventure Exit
tool.apadventure_exit.shortname=Exit
tool.apadventure_exit.desc=Place exits that players will leave the map through
tool.apadventure_exit.left=Place/Update exit
tool.apadventure_exit.right=Copy Settings
tool.apadventure_exit.region_help=The region this exit is in. The Generator won't use the exit if it can't find a region with this name.
tool.apadventure_exit.name_ui=Exit Name
tool.apadventure_exit.name_help=The name of this exit. You can place multiple exits with the same name if you want.
tool.apadventure_exit.match_names_info=All exits sharing the same name should also be in the same region. If they are not, the game will arbitrarily pick one when creating the logic files for the Generator. It may even pick a region name that doesn't exist, causing all exits with that name to go unused. 

tool.apadventure_entrance.name=apAdventure Entrance
tool.apadventure_entrance.shortname=Entrance
tool.apadventure_entrance.desc=Place entrances that players will enter the map through
tool.apadventure_entrance.left=Place/Update entrance
tool.apadventure_entrance.right=Copy Settings
tool.apadventure_entrance.reload=Place entrance at your feet
tool.apadventure_entrance.region_help=The region this entrance is in. The Generator won't use the entrance if it can't find a region with this name.
tool.apadventure_entrance.name_ui=Entrance Name
tool.apadventure_entrance.name_help=The name of this entrance. You can (and should) place multiple entrances with the same name to give players alternative spawn points in case one of the others is obstructed.
tool.apadventure_entrance.match_names_info=All entrances sharing the same name should also be in the same region. If they are not, the game will arbitrarily pick a region when creating the logic files for the Generator. It may even pick a region name that doesn't exist, causing all entrances with that name to go unused. 

tool.apadventure_start.name=apAdventure Start Point
tool.apadventure_start.shortname=Start Point
tool.apadventure_start.desc=Place Start Points that players may start their run on
tool.apadventure_start.left=Place/Update Start
tool.apadventure_start.right=Copy Settings
tool.apadventure_start.reload=Place Start at your feet
tool.apadventure_start.region_help=The region this Start Point is in. The Generator won't use it if it can't find a region with this name.
tool.apadventure_start.help1=Start Points tell the Generator that a run can be started from a certain region in a certain map. Don't place them in maps/regions where you don't want runs to start from.
tool.apadventure_start.help2=Start Points also function as Spawn Points. You can (and should) place multiple Start Points in the same region to give players alternative Spawn Points in case one of the others is obstructed.

tool.apadventure_location.name=apAdventure Location
tool.apadventure_location.shortname=Location
tool.apadventure_location.desc=Place locations
tool.apadventure_location.left=Place/Update locations
tool.apadventure_location.right=Copy Settings
tool.apadventure_location.region_help=The region containing this location. The Generator won't use the location if it can't find a region with this name.
tool.apadventure_location.name_ui=Location Name
tool.apadventure_location.name_help=The name of this location. There shouldn't be two locations with the same name on the same map. It should also not be a number.
tool.apadventure_location.isdummy=Is Dummy
tool.apadventure_location.isdummy_help=Whether or not this location is a dummy location. Dummy locations won't actually be placed when the Config is loaded, and are instead intended to be sent through other means like the Config Script or Hammer I/O, so this won't be of much use if you're not a lua coder or mapper.

tool.apadventure_inspector.name=apAdventure Inspector
tool.apadventure_inspector.shortname=Inspector
tool.apadventure_inspector.desc=Shows information about normally invisible entities
tool.apadventure_inspector.left=Hide/Unhide Inspector Info
tool.apadventure_inspector.reload=Request update
tool.apadventure_inspector.help1=This tool allows players to get some info about map entities that aren't normally visible. Currently it only shows info about point_template entities.
tool.apadventure_inspector.help_point_template=point_template entities are used to spawn other entities when they are activated. For example, most HL2 maps have a point_template near their starting point that spawns in a bunch of supplies for players who enter the map without transitioning in from another map, like through console commands or through the chapter select. Because apAdventure doesn't use the HL2 level transition system, these will always spawn, which we usually don't want. Since these supplies are spawned in through another entity, they're technically not map-created entities, so they can't be deleted with the Delete Marker Tool. For cases like these, this tool can be used to find the point_template spawning them and delete that instead.

apadventure.ui.accessedit.label=Access Editor

apadventure.editor.nicename.label=Nice Name
apadventure.editor.walkspd.label=Walk Speed
apadventure.editor.walkspd.help=The players movement speed while holding down the walk button (alt by default) in units per second. Actually referred to as "SlowWalkSpeed" in gMods code.
apadventure.editor.runspd.label=Run Speed
apadventure.editor.runspd.help=The players normal movement speed in units per second. Actually referred to as "WalkSpeed" in gMods code.
apadventure.editor.sprintspd.label=Sprint Speed
apadventure.editor.sprintspd.help=The players movement speed while holding down the sprint button (shift by default) in units per second. Actually referred to as "RunSpeed" in gMods code.
apadventure.editor.jump.label=Jump Power
apadventure.editor.jump.help=How much velocity will be applied to the player when they jump.
apadventure.editor.grav.label=Gravity
apadventure.editor.frctn.label=Player Friction
apadventure.editor.accel.label=Player Acceleration
apadventure.editor.airaccel.label=Player Air Acceleration
apadventure.editor.airaccel.help=What sv_airacceleration should be set to when the config is loaded. This value controls how much speed players can gain from Air Strafing. BHop and Surf maps usually expect this value to be higher than normal.
apadventure.editor.stopspd.label=Player Stop Speed
apadventure.editor.hev.label=Enable HL2 HEV Suit functionality (Energy drain from sprinting, using flashlight, etc.)
apadventure.editor.respawn.label=Allow players to respawn after death
apadventure.editor.respawn.help=Normally, when a player dies, they will have to wait until all players have died, causing the config to be reloaded. This setting allows players to respawn immediately, as many times as they want, as if they were playing sandbox.
apadventure.editor.godmode.label=Disable damage to players
apadventure.editor.godmode.help=Prevents players from taking damage from most sources, they may still die or lose HP to things that set their health to a certain value or kill them directly without dealing damage, such as killbinds, similar to the sbox_godmode cvar in sandbox.

apadventure.editor.mapitem.amount.label=Amount
apadventure.editor.mapitem.progression.label=Progression
apadventure.editor.mapitem.useful.label=Useful
apadventure.editor.mapitem.trap.label=Trap
apadventure.editor.mapitem.skipbalance.label=Skip Progression Balancing
apadventure.editor.mapitem.deprio.label=Deprioritize (won't appear on priority locations)

apadventure.editor.regammo.label=Ammo Availability

apadventure.connect.address=Address
apadventure.connect.slotname=Slot Name
apadventure.connect.password=Password
apadventure.connect.connect=Connect