
apadventure.mapcfg.hl2.d2_prison_07.waveclearhint1=You have already cleared this wave and can skip it by not touching the turrets.
apadventure.mapcfg.hl2.d2_prison_07.waveclearhint2=The force fields are down and won't turn on unless you decide to start the wave again.