
apadventure.mapcfg.hl2.d2_prison_07.waveclearhint1=You have already cleared this wave and can skip it by not touching the turrets.
apadventure.mapcfg.hl2.d2_prison_07.waveclearhint2=The force fields are down and won't turn on unless you decide to start the wave again.

apadventure.mapcfg.hl2.d3_c17_03.bindhint1=NPCs can commanded with the "impulse 50" command, which is unbound by default.
apadventure.mapcfg.hl2.d3_c17_03.bindhint2=The bind menu has a preset to help you bind this command.